### PR TITLE
Fix crash when the URL of skull profiles is not valid.

### LINKED ISSUE #254: [Bug] 客户端遇到头颅时崩溃
### Describe the bug

可能是因为玩家头颅的问题,当我移除服务器的头颅时或删除CSL不会崩溃

### Steps to reproduce

```bash
1. 当拿到这个头颅物品时客户端崩溃
```

### Link to crash-report if applicable

https://mclo.gs/rnuQmuw#L15

### Link to CustomSkinLoader.log if applicable

https://mclo.gs/DaKWCF9

### Link to latest.log if applicable

https://mclo.gs/SohwWda

### [Only Forge User] Link to Forge Log  if applicable

https://mclo.gs/u9f1mGH

### Mod Version

CustomSkinLoader_ForgeLegacy-14.16

### Minecraft Version

1.12.2

### Minecraft Launcher Name and Version

PCL2

### Mod Loader

Forge

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

- [X] This problem is triggered in the latest version of the mod (if not the latest please upgrade the mod first)

### PR DESCRIPTION
**Pull request by ZekerZhayard**
Fix #254

### CODE REVIEW

**Comment by XiaoPangxie732** [comment]
为什么不用orElseGet捏（

File: Common/src/main/java/customskinloader/fake/FakeMinecraftProfileTexture.java [hunk 1]
```diff
@@ -35,7 +36,7 @@ public String getRawUrl() {
 
     @Override
     public String getHash() {
-        return this.info.hash;
+        return Optional.ofNullable(this.info.hash).orElse(super.getHash());
```
Comment (xfl03) [inline Common/src/main/java/customskinloader/fake/FakeMinecraftProfileTexture.java]: `orElseGet` or conditional operator.

**Review by xfl03 — CHANGES_REQUESTED** [review]

**Review by xfl03 — APPROVED** [review]
